import time
import httpx

from app.core.config import settings

_ollama_available: bool | None = None
_last_check_time: float = 0.0


def is_ollama_available() -> bool:
    """Checks if the local Ollama daemon is reachable, caching result for 60s."""
    global _ollama_available, _last_check_time
    now = time.time()
    if _ollama_available is not None and (now - _last_check_time) < 60.0:
        return _ollama_available

    try:
        res = httpx.get(
            f"{settings.ollama_base_url}/api/tags",
            timeout=httpx.Timeout(0.5, connect=0.1),
        )
        _ollama_available = res.status_code == 200
    except Exception:
        _ollama_available = False

    _last_check_time = now
    return _ollama_available


def ask_ollama(prompt: str) -> str:
    """
    Send a prompt to the locally running Ollama model
    and return its response.
    """
    if not is_ollama_available():
        return "No response was generated by the AI model."

    try:
        response = httpx.post(
            f"{settings.ollama_base_url}/api/generate",
            json={
                "model": settings.ollama_model,
                "prompt": prompt,
                "stream": False,
            },
            timeout=httpx.Timeout(10.0, connect=0.5),
        )
        response.raise_for_status()
        data = response.json()
        return data.get(
            "response",
            "No response was generated by the AI model.",
        )
    except Exception:
        return "No response was generated by the AI model."