"""create trains table

Revision ID: 367e6abb9624
Revises: b088be577af4
Create Date: 2026-09-08 19:40:35.376354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367e6abb9624'
down_revision: Union[str, Sequence[str], None] = 'b088be577af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=False),
    sa.Column('source_station_code', sa.String(length=20), nullable=False),
    sa.Column('destination_station_code', sa.String(length=20), nullable=False),
    sa.Column('current_station_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('speed_kmph', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_current_station_code'), 'trains', ['current_station_code'], unique=False)
    op.create_index(op.f('ix_trains_destination_station_code'), 'trains', ['destination_station_code'], unique=False)
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_source_station_code'), 'trains', ['source_station_code'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_source_station_code'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_index(op.f('ix_trains_destination_station_code'), table_name='trains')
    op.drop_index(op.f('ix_trains_current_station_code'), table_name='trains')
    op.drop_table('trains')
    # ### end Alembic commands ###
