"""create blocks table

Revision ID: 8a61c95d4950
Revises: a403c15add46
Create Date: 2026-09-05 09:46:04.337497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a61c95d4950'
down_revision: Union[str, Sequence[str], None] = 'a403c15add46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('start_station_code', sa.String(length=20), nullable=False),
    sa.Column('end_station_code', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_code'), 'blocks', ['code'], unique=True)
    op.create_index(op.f('ix_blocks_end_station_code'), 'blocks', ['end_station_code'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_start_station_code'), 'blocks', ['start_station_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_start_station_code'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_end_station_code'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_code'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
