"""create maintenance table

Revision ID: b088be577af4
Revises: 8a61c95d4950
Create Date: 2026-09-05 10:15:37.898677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b088be577af4'
down_revision: Union[str, Sequence[str], None] = '8a61c95d4950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_code', sa.String(length=30), nullable=False),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_block_code'), 'maintenance', ['block_code'], unique=False)
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_block_code'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
